# Generated by Django 3.2 on 2022-12-17 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65, unique=True, verbose_name='Nombre')),
                ('status', models.CharField(choices=[('u', 'Tareas no iniciada'), ('o', 'En Curso'), ('f', 'Finalizada')], max_length=1, verbose_name='Estado')),
            ],
        ),
    ]
